m2w64_c_compiler_version:        # [win]
  - 13                           # [win]
m2w64_cxx_compiler_version:      # [win]
  - 13                           # [win]
m2w64_fortran_compiler_version:  # [win]
  - 13                           # [win]
m2w64_c_stdlib_version:          # [win]
  - 12                           # [win]
